//! Diagrammer Relay binary entry point.
//!
//! Subcommands:
//!   `relay init`   — write a placeholder `relay.toml`. Full TOML
//!                    schema (storage backend, JWT secret, TLS) lands
//!                    in Slice D alongside the `Storage` trait.
//!   `relay serve`  — start the WebSocket sync server on the
//!                    configured port using `./data` as the storage
//!                    root. MCP / REST API wiring arrives in Slice D.
//!
//! Slice C.4 keeps this intentionally thin: the goal is to prove the
//! lifted modules (auth/, server/, mcp/) compose into a runnable
//! binary. Behavior matches what the Tauri host previously did when it
//! spun up Protected Local mode internally.

use std::path::PathBuf;
use std::sync::Arc;

use clap::{Parser, Subcommand};

use diagrammer_relay::auth::UserStore;
use diagrammer_relay::server::WebSocketServer;

/// Default placeholder content for a fresh `relay.toml`.
///
/// Slice D replaces this with a real schema (`[server]`, `[storage]`,
/// `[auth]`, `[tls]`) and a freshly-rolled JWT secret. The placeholder
/// exists so `relay init` is observable today.
const PLACEHOLDER_RELAY_TOML: &str = r#"# diagrammer-relay configuration
# This is a Slice C.4 placeholder; the real schema lands in Slice D.

[server]
listen = "0.0.0.0:9876"

[storage]
backend = "filesystem"
path = "./data"

[auth]
# A real JWT secret is generated by `relay init` in Slice D.
# For now the relay falls back to a hard-coded development secret
# and prints a loud warning.
"#;

#[derive(Parser, Debug)]
#[command(name = "relay", version, about = "Diagrammer Relay server")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Generate a `relay.toml` with default settings.
    Init {
        #[arg(long, default_value = "relay.toml")]
        config: PathBuf,
        /// Overwrite an existing config file.
        #[arg(long)]
        force: bool,
    },
    /// Start the relay server.
    Serve {
        /// Path to the relay config (Slice D will actually read it).
        #[arg(long, default_value = "relay.toml")]
        config: PathBuf,
        /// TCP port to listen on. Defaults to 9876.
        #[arg(long, default_value_t = 9876)]
        port: u16,
        /// Storage root. Defaults to `./data`.
        #[arg(long, default_value = "data")]
        data_dir: PathBuf,
    },
}

fn main() -> anyhow::Result<()> {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    let cli = Cli::parse();
    match cli.command {
        Command::Init { config, force } => run_init(config, force),
        Command::Serve {
            config,
            port,
            data_dir,
        } => {
            let runtime = tokio::runtime::Builder::new_multi_thread()
                .enable_all()
                .build()?;
            runtime.block_on(run_serve(config, port, data_dir))
        }
    }
}

fn run_init(config: PathBuf, force: bool) -> anyhow::Result<()> {
    if config.exists() && !force {
        anyhow::bail!(
            "{} already exists. Pass --force to overwrite.",
            config.display()
        );
    }
    std::fs::write(&config, PLACEHOLDER_RELAY_TOML)?;
    log::info!("wrote placeholder config to {}", config.display());
    log::warn!("Slice C.4 placeholder — the real schema + JWT secret generator lands in Slice D");
    Ok(())
}

async fn run_serve(config: PathBuf, port: u16, data_dir: PathBuf) -> anyhow::Result<()> {
    if !config.exists() {
        log::warn!(
            "{} does not exist; running with built-in defaults. Use `relay init` to create one.",
            config.display()
        );
    }

    std::fs::create_dir_all(&data_dir)?;

    let users_path = data_dir.join("users.json");
    let user_store = Arc::new(UserStore::with_persistence(
        users_path.to_string_lossy().into_owned(),
    ));

    let server = WebSocketServer::new();
    server.set_app_data_dir(data_dir.clone()).await;
    server.set_user_store(user_store).await;
    // JWT secret + token config keep their built-in defaults for now.
    // Slice D loads them from `relay.toml` and rolls a per-deploy
    // secret in `relay init`.
    log::warn!("running with the built-in development JWT secret — do not use in production");

    let bound = server
        .start(port)
        .await
        .map_err(|e| anyhow::anyhow!("failed to start relay: {}", e))?;
    log::info!("diagrammer-relay listening on {}", bound);
    log::info!("storage root: {}", data_dir.display());
    log::info!("press Ctrl-C to shut down");

    tokio::signal::ctrl_c().await?;
    log::info!("shutdown requested");

    server
        .stop()
        .await
        .map_err(|e| anyhow::anyhow!("failed to stop relay cleanly: {}", e))?;
    Ok(())
}
