/**
 * mermaid-to-svg.ts — convert the docs-site's flat Mermaid flowcharts into
 * native DocuShark SVGs (dogfooding our own import + export engine), and rewrite
 * the markdown fences to reference the generated assets.
 *
 * Run: `bun scripts/mermaid-to-svg.ts`  (from docushark-app/)
 *
 * Scope (JP-312 Phase 1): only the FLAT flowcharts in the allowlisted files.
 * Subgraph-structured flowcharts (architecture / state-management /
 * collaboration-protocol / interface-tour) and every `sequenceDiagram` stay as
 * Mermaid — the flowchart importer flattens subgraphs and doesn't do sequence
 * diagrams. The script fails loud if a target block doesn't import cleanly, so
 * drift can't silently produce a broken SVG.
 *
 * Pipeline: mermaidAdapter.import → on-brand style pass → exportToSvg →
 * "Generated by DocuShark" caption → docs-site/public/diagrams/<slug>.svg.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import './_defines'; // must precede any ../src import (shims Vite defines)
import '../src/shapes/registerBuiltInShapes';
import { mermaidAdapter } from '../src/shapes/import/adapters/mermaidAdapter';
import { exportToSvg, type ExportData } from '../src/utils/exportUtils';
import type { Shape } from '../src/shapes/Shape';

const HERE = dirname(fileURLToPath(import.meta.url));
const APP_ROOT = join(HERE, '..');
const DOCS = join(APP_ROOT, 'docs-site');
const OUT_DIR = join(DOCS, 'public', 'diagrams');

// On-brand palette (mirrors src/index.css brand tokens). These flat diagrams are
// homogeneous "process" flows, so one consistent navy-on-warm-paper style reads
// cleaner than the importer's generic blue.
const PAPER = '#f7f4ec'; // canvas-bg — the diagram sits on a warm-paper card
const NODE_FILL = '#1f3354'; // navy-700
const NODE_STROKE = '#0e1c30'; // navy-900
const NODE_LABEL = '#f6f4ec'; // warm paper, on dark node
const EDGE_STROKE = '#2b466e'; // navy-600 — reads against both paper and nodes
const CAPTION = 'Generated by DocuShark';

interface Target {
  /** path relative to docs-site/ */
  file: string;
  /** one entry per FLAT flowchart block in the file, in document order */
  diagrams: Array<{ slug: string; alt: string }>;
}

const TARGETS: Target[] = [
  {
    file: 'developer/core-systems.md',
    diagrams: [{ slug: 'coordinate-transform-pipeline', alt: 'Coordinate transform pipeline' }],
  },
  {
    file: 'developer/creating-prose-helpers.md',
    diagrams: [{ slug: 'prose-helper-dataflow', alt: 'Prose helper data flow' }],
  },
  {
    file: 'developer/creating-shapes.md',
    diagrams: [
      { slug: 'shape-system-registry', alt: 'Shape system registry' },
      { slug: 'world-to-local-transform', alt: 'World-to-local point transform' },
    ],
  },
];

const FENCE = /```mermaid\n([\s\S]*?)\n```/g;
const isFlowchart = (body: string) => /^\s*(flowchart|graph)\b/i.test(body);

/** Apply the on-brand style pass to imported shapes (mutates in place). */
function styleShapes(shapes: Shape[]): void {
  for (const s of shapes) {
    if (s.type === 'rectangle') {
      Object.assign(s, {
        fill: NODE_FILL,
        stroke: NODE_STROKE,
        strokeWidth: 2,
        cornerRadius: 8,
        labelColor: NODE_LABEL,
        labelFontSize: 13,
      });
    } else if (s.type === 'connector') {
      Object.assign(s, {
        stroke: EDGE_STROKE,
        strokeWidth: 2,
        labelColor: EDGE_STROKE,
        labelFontSize: 12,
        labelOffsetY: -12, // lift edge labels clear of the line
      });
    }
  }
}

/** Add the height for a caption band + the "Generated by DocuShark" text. */
function withCaption(svg: string): string {
  const m = svg.match(/width="([\d.]+)" height="([\d.]+)" viewBox="0 0 [\d.]+ [\d.]+"/);
  if (!m) throw new Error('could not parse SVG header for caption injection');
  const w = parseFloat(m[1]!);
  const h = parseFloat(m[2]!);
  const band = 26;
  const nh = h + band;
  const caption = `  <text x="${w - 10}" y="${h + 16}" font-family="sans-serif" font-size="11" text-anchor="end" fill="#8d9bb1">${CAPTION}</text>`;
  return svg
    // grow the canvas to fit the caption band
    .replace(
      `width="${m[1]}" height="${m[2]}" viewBox="0 0 ${m[1]} ${m[2]}"`,
      `width="${m[1]}" height="${nh}" viewBox="0 0 ${m[1]} ${nh}"`,
    )
    // extend the paper card under the caption band (background rect is first)
    .replace(
      `<rect x="0" y="0" width="${m[1]}" height="${m[2]}" fill="${PAPER}"/>`,
      `<rect x="0" y="0" width="${m[1]}" height="${nh}" fill="${PAPER}"/>`,
    )
    .replace('</svg>', `${caption}\n</svg>`);
}

async function buildSvg(mermaid: string): Promise<string> {
  const result = await mermaidAdapter.import(mermaid);
  const blocking = (result.warnings ?? []).filter(
    (w) => w.kind === 'parse' || w.kind === 'unsupported-diagram' || w.kind === 'subgraph',
  );
  if (blocking.length > 0) {
    throw new Error(`import warnings: ${blocking.map((w) => `${w.kind}: ${w.detail}`).join('; ')}`);
  }
  if (result.shapes.length === 0) throw new Error('import produced no shapes');

  styleShapes(result.shapes);

  const shapesMap: Record<string, Shape> = {};
  const shapeOrder: string[] = [];
  for (const s of result.shapes) {
    shapesMap[s.id] = s;
    shapeOrder.push(s.id);
  }
  const data: ExportData = { shapes: shapesMap, shapeOrder, selectedIds: [] };
  const svg = exportToSvg(data, {
    format: 'svg',
    scope: 'all',
    scale: 1,
    background: PAPER,
    padding: 28,
    filename: 'diagram',
    flattenGroups: false,
  });
  return withCaption(svg);
}

async function main(): Promise<void> {
  mkdirSync(OUT_DIR, { recursive: true });
  let total = 0;

  for (const target of TARGETS) {
    const path = join(DOCS, target.file);
    const original = readFileSync(path, 'utf8');

    // Collect flowchart blocks in document order (skip sequenceDiagram etc.).
    const flowcharts: Array<{ match: string; body: string }> = [];
    for (const fence of original.matchAll(FENCE)) {
      if (isFlowchart(fence[1]!)) flowcharts.push({ match: fence[0], body: fence[1]! });
    }

    if (flowcharts.length !== target.diagrams.length) {
      throw new Error(
        `${target.file}: expected ${target.diagrams.length} flat flowchart(s) but found ${flowcharts.length} — manifest drift, aborting.`,
      );
    }

    let content = original;
    for (let i = 0; i < flowcharts.length; i++) {
      const { match, body } = flowcharts[i]!;
      const { slug, alt } = target.diagrams[i]!;
      const svg = await buildSvg(body);
      writeFileSync(join(OUT_DIR, `${slug}.svg`), svg, 'utf8');
      content = content.replace(match, `![${alt}](/diagrams/${slug}.svg)`);
      const nodes = (svg.match(/<rect /g) ?? []).length - 1; // minus the paper bg
      const edges = (svg.match(/<line /g) ?? []).length;
      console.log(`  ${target.file} → ${slug}.svg  (~${nodes} nodes, ${edges} edges)`);
      total++;
    }

    if (content !== original) writeFileSync(path, content, 'utf8');
  }

  console.log(`\nConverted ${total} flowchart(s) → ${OUT_DIR}`);
}

main().catch((err) => {
  console.error('mermaid-to-svg failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
