/**
 * mermaid-to-svg.ts — convert the docs-site's flat Mermaid flowcharts into
 * native DocuShark SVGs (dogfooding our own import + export engine), and rewrite
 * the markdown fences to reference the generated assets.
 *
 * Run: `bun scripts/mermaid-to-svg.ts`  (from docushark-app/)
 *
 * Scope (JP-312 Phase 1): only the FLAT flowcharts in the allowlisted files.
 * Subgraph-structured flowcharts (architecture / state-management /
 * collaboration-protocol / interface-tour) and every `sequenceDiagram` stay as
 * Mermaid — the flowchart importer flattens subgraphs and doesn't do sequence
 * diagrams. The script fails loud if a target block doesn't import cleanly, so
 * drift can't silently produce a broken SVG.
 *
 * Pipeline: mermaidAdapter.import → on-brand style pass → exportToSvg →
 * "Generated by DocuShark" caption → docs-site/public/diagrams/<slug>.svg.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import './_defines'; // must precede any ../src import (shims Vite defines)
import '../src/shapes/registerBuiltInShapes';
import { mermaidAdapter } from '../src/shapes/import/adapters/mermaidAdapter';
import { exportToSvg, type ExportData } from '../src/utils/exportUtils';
import type { Shape, ConnectorShape } from '../src/shapes/Shape';
import { SpatialIndex } from '../src/engine/SpatialIndex';
import { calculateConnectorWaypoints } from '../src/engine/OrthogonalRouter';
import { chooseConnectorAnchors, updateConnectorEndpoints } from '../src/shapes/Connector';

const HERE = dirname(fileURLToPath(import.meta.url));
const APP_ROOT = join(HERE, '..');
const DOCS = join(APP_ROOT, 'docs-site');
const OUT_DIR = join(DOCS, 'public', 'diagrams');

// On-brand palette (mirrors src/index.css brand tokens). These flat diagrams are
// homogeneous "process" flows, so one consistent navy-on-warm-paper style reads
// cleaner than the importer's generic blue.
const PAPER = '#f7f4ec'; // canvas-bg — the diagram sits on a warm-paper card
const NODE_FILL = '#1f3354'; // navy-700
const NODE_STROKE = '#0e1c30'; // navy-900
const NODE_LABEL = '#f6f4ec'; // warm paper, on dark node
const EDGE_STROKE = '#2b466e'; // navy-600 — reads against both paper and nodes
const CAPTION = 'Generated by DocuShark';

interface Diagram {
  /** path relative to docs-site/ */
  file: string;
  slug: string;
  alt: string;
  /**
   * The Mermaid source — kept here as the source of truth (not read back from
   * the markdown), so the script stays idempotent/re-runnable after the fence
   * has already been replaced with the generated image. Labels use `\\n` for the
   * literal `\n` line-break marker Mermaid expects. (Plain template literals, not
   * `String.raw`: under bun `String.raw` mangles non-ASCII like the middot into a
   * literal backslash-u escape.)
   */
  mermaid: string;
}

const DIAGRAMS: Diagram[] = [
  {
    file: 'developer/core-systems.md',
    slug: 'coordinate-transform-pipeline',
    alt: 'Coordinate transform pipeline',
    mermaid: `flowchart TD
  A["Screen Space\\n(canvas pixels)"] -->|camera.screenToWorld| B["World Space\\n(infinite 2D plane)"]
  B -->|shape.worldToLocal| C["Local Space\\n(for rotated shapes)"]`,
  },
  {
    file: 'developer/creating-prose-helpers.md',
    slug: 'prose-helper-dataflow',
    alt: 'Prose helper data flow',
    mermaid: `flowchart LR
  A["Editor node\\n(Tiptap)"] -->|getHTML| B["Local persistence\\n(richText JSON)"]
  A -->|y-prosemirror| C["Collab Y.Doc\\n(relay round-trip)"]
  A --> D["PDF / MCP get_prose"]`,
  },
  {
    file: 'developer/creating-shapes.md',
    slug: 'shape-system-registry',
    alt: 'Shape system registry',
    mermaid: `flowchart LR
  A["Shape Data\\n(plain object)"] --> B["ShapeRegistry"]
  B --> C["ShapeHandler\\nrender · hitTest · getBounds\\ngetHandles · create · getAnchors"]
  B --> D["ShapeMetadata\\nname · icon · properties\\ncategory · defaults"]`,
  },
  {
    // Laid out top-to-bottom (vertical) to match the coordinate-pipeline diagram.
    file: 'developer/creating-shapes.md',
    slug: 'world-to-local-transform',
    alt: 'World-to-local point transform',
    mermaid: `flowchart TD
  A["World Point\\n(x, y)"] -->|"subtract (shape.x, shape.y)"| B["Translated"]
  B -->|"rotate by -shape.rotation"| C["Local Point"]`,
  },
];

/** Apply the on-brand style pass to imported shapes (mutates in place). */
function styleShapes(shapes: Shape[]): void {
  for (const s of shapes) {
    if (s.type === 'rectangle') {
      Object.assign(s, {
        fill: NODE_FILL,
        stroke: NODE_STROKE,
        strokeWidth: 2,
        cornerRadius: 8,
        labelColor: NODE_LABEL,
        labelFontSize: 13,
      });
    } else if (s.type === 'connector') {
      Object.assign(s, {
        stroke: EDGE_STROKE,
        strokeWidth: 2,
        labelColor: EDGE_STROKE,
        labelStrokeColor: PAPER, // legibility halo where a label crosses a node
        labelFontSize: 12,
        labelOffsetY: -12, // lift edge labels clear of the line
      });
    }
  }
}

/**
 * Route connectors the way the editor / import pipeline does
 * (`documentStore.rebuildAllConnectorRoutes`): re-seat anchors, re-pull
 * endpoints, then compute orthogonal waypoints — so the exported SVG follows
 * the real routed path instead of a straight start→end line.
 */
function routeConnectors(shapes: Shape[]): void {
  const map: Record<string, Shape> = {};
  for (const s of shapes) map[s.id] = s;
  const obstacleIndex = new SpatialIndex();
  obstacleIndex.rebuild(shapes);

  for (const s of shapes) {
    if (s.type !== 'connector') continue;
    const c = s as ConnectorShape;
    const startShape = c.startShapeId ? map[c.startShapeId] : undefined;
    const endShape = c.endShapeId ? map[c.endShapeId] : undefined;
    if (startShape && endShape) {
      const anchors = chooseConnectorAnchors(startShape, endShape);
      if (anchors) {
        c.startAnchor = anchors.startAnchor;
        c.endAnchor = anchors.endAnchor;
      }
    }
    const ep = updateConnectorEndpoints(c, map);
    if (ep.x !== undefined) c.x = ep.x;
    if (ep.y !== undefined) c.y = ep.y;
    if (ep.x2 !== undefined) c.x2 = ep.x2;
    if (ep.y2 !== undefined) c.y2 = ep.y2;
    if (c.routingMode === 'orthogonal') {
      c.waypoints = calculateConnectorWaypoints(c, map, obstacleIndex) ?? [];
    }
  }
}

/** Add the height for a caption band + the "Generated by DocuShark" text. */
function withCaption(svg: string): string {
  const m = svg.match(/width="([\d.]+)" height="([\d.]+)" viewBox="0 0 [\d.]+ [\d.]+"/);
  if (!m) throw new Error('could not parse SVG header for caption injection');
  const w = parseFloat(m[1]!);
  const h = parseFloat(m[2]!);
  const band = 26;
  const nh = h + band;
  const caption = `  <text x="${w - 10}" y="${h + 16}" font-family="sans-serif" font-size="11" text-anchor="end" fill="#8d9bb1">${CAPTION}</text>`;
  return svg
    // grow the canvas to fit the caption band
    .replace(
      `width="${m[1]}" height="${m[2]}" viewBox="0 0 ${m[1]} ${m[2]}"`,
      `width="${m[1]}" height="${nh}" viewBox="0 0 ${m[1]} ${nh}"`,
    )
    // extend the paper card under the caption band (background rect is first)
    .replace(
      `<rect x="0" y="0" width="${m[1]}" height="${m[2]}" fill="${PAPER}"/>`,
      `<rect x="0" y="0" width="${m[1]}" height="${nh}" fill="${PAPER}"/>`,
    )
    .replace('</svg>', `${caption}\n</svg>`);
}

async function buildSvg(mermaid: string): Promise<string> {
  const result = await mermaidAdapter.import(mermaid);
  const blocking = (result.warnings ?? []).filter(
    (w) => w.kind === 'parse' || w.kind === 'unsupported-diagram' || w.kind === 'subgraph',
  );
  if (blocking.length > 0) {
    throw new Error(`import warnings: ${blocking.map((w) => `${w.kind}: ${w.detail}`).join('; ')}`);
  }
  if (result.shapes.length === 0) throw new Error('import produced no shapes');

  styleShapes(result.shapes);
  routeConnectors(result.shapes);

  const shapesMap: Record<string, Shape> = {};
  const shapeOrder: string[] = [];
  for (const s of result.shapes) {
    shapesMap[s.id] = s;
    shapeOrder.push(s.id);
  }
  const data: ExportData = { shapes: shapesMap, shapeOrder, selectedIds: [] };
  const svg = exportToSvg(data, {
    format: 'svg',
    scope: 'all',
    scale: 1,
    background: PAPER,
    padding: 28,
    filename: 'diagram',
    flattenGroups: false,
  });
  return withCaption(svg);
}

async function main(): Promise<void> {
  mkdirSync(OUT_DIR, { recursive: true });

  for (const d of DIAGRAMS) {
    const svg = await buildSvg(d.mermaid);
    writeFileSync(join(OUT_DIR, `${d.slug}.svg`), svg, 'utf8');

    // Idempotent markdown rewrite: replace the source fence with the image ref
    // on the first run; on later runs the fence is gone and the ref already
    // present, so it's a no-op.
    const path = join(DOCS, d.file);
    const md = readFileSync(path, 'utf8');
    const imageRef = `![${d.alt}](/diagrams/${d.slug}.svg)`;
    const fence = '```mermaid\n' + d.mermaid + '\n```';
    if (md.includes(fence)) {
      writeFileSync(path, md.replace(fence, imageRef), 'utf8');
    } else if (!md.includes(imageRef)) {
      console.warn(`  WARN ${d.file}: neither source fence nor "${d.slug}" image ref found — markdown left unchanged`);
    }

    const nodes = (svg.match(/<rect /g) ?? []).length - 1; // minus the paper bg
    const edges = (svg.match(/<(?:line|polyline) /g) ?? []).length;
    console.log(`  ${d.file} → ${d.slug}.svg  (~${nodes} nodes, ${edges} edges)`);
  }

  console.log(`\nGenerated ${DIAGRAMS.length} diagram(s) → ${OUT_DIR}`);
}

main().catch((err) => {
  console.error('mermaid-to-svg failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
