/**
 * Relay↔editor Yjs wire-contract test (JP-326) — the editor half of the
 * cross-language corpus under `relay/tests/yjs-fixtures/`.
 *
 * The relay's Rust CRDT library (yrs) happily decodes its own output, so a
 * relay-side test can never prove a browser can. This suite applies the
 * relay's actual bytes — per-op WebSocket sync frames and the DSKY binary
 * sidecar — through the editor's REAL decode paths:
 *
 *  - `stripSidecarHeader` + `applyUpdate`, exactly as the JP-422 offline
 *    prefetch does;
 *  - `y-protocols readSyncMessage` with NO errorHandler, byte-identical to
 *    `UnifiedSyncProvider.handleSyncMessage` — where a decode throw is
 *    swallowed as a `console.error` ("Caught error while handling a Yjs
 *    update") and the client's sync silently jams. The spy below turns that
 *    swallow into a test failure.
 *
 * It then closes the content triangle: the CRDT state as y-prosemirror
 * projects it must equal the relay's own `expected.html` as the editor's
 * Tiptap schema parses it. Both 2026-07-12 incidents — the yrs-only
 * `ContentMove` poison (wire ref 11, undecodable by yjs) and the unanchored
 * index-0 insert landing in the wrong slot after re-integration — fail this
 * suite in milliseconds.
 *
 * Fixtures are generated by `relay/tests/yjs_fixtures.rs`
 * (`cargo test regenerate_yjs_fixtures -- --ignored`); a relay-side drift
 * test keeps them byte-fresh.
 */

import { describe, it, expect, vi } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Doc as YDoc, applyUpdate } from 'yjs';
import * as decoding from 'lib0/decoding';
import * as encoding from 'lib0/encoding';
import * as syncProtocol from 'y-protocols/sync';
import { yXmlFragmentToProseMirrorRootNode } from 'y-prosemirror';
import { Editor, getSchema } from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';

import { MESSAGE_SYNC } from './protocol';
import { stripSidecarHeader } from './prefetchYdoc';
import { sharedProseExtensions } from '../ui/TiptapEditor';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = resolve(__dirname, '../../relay/tests/yjs-fixtures');

/** Mirrors `meta.json` as written by `relay/tests/yjs_fixtures.rs`. */
interface ScenarioMeta {
  description: string;
  pageId: string | null;
  serverVersion: number;
  poison: boolean;
  frames: string[];
  sidecar: string;
  expectedHtml: string | null;
}

interface Scenario {
  name: string;
  dir: string;
  meta: ScenarioMeta;
}

function loadScenarios(): Scenario[] {
  return readdirSync(FIXTURES_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const dir = join(FIXTURES_DIR, entry.name);
      const meta = JSON.parse(readFileSync(join(dir, 'meta.json'), 'utf8')) as ScenarioMeta;
      return { name: entry.name, dir, meta };
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}

function readBytes(scenario: Scenario, rel: string): Uint8Array {
  return new Uint8Array(readFileSync(join(scenario.dir, rel)));
}

// Mirror the collaborative editor's schema construction (the same shape as
// proseSchemaContract.test.ts — keep the two in sync).
const extensions = [
  StarterKit.configure({
    heading: { levels: [1, 2, 3, 4, 5, 6] },
    codeBlock: false,
    history: false,
  }),
  ...sharedProseExtensions,
];
const schema = getSchema(extensions);

const SWALLOWED_ERROR = 'Caught error while handling a Yjs update';

/**
 * Apply one relay broadcast frame exactly as
 * `UnifiedSyncProvider.handleSyncMessage` does: skip the `MESSAGE_SYNC`
 * prefix, then `readSyncMessage` with no errorHandler. A decode failure does
 * NOT throw here — y-protocols catches it and logs `SWALLOWED_ERROR`, which
 * the caller's console spy must inspect.
 */
function applyFrameLikeProduction(doc: YDoc, frame: Uint8Array): void {
  const decoder = decoding.createDecoder(frame);
  const messageType = decoding.readVarUint(decoder);
  expect(messageType).toBe(MESSAGE_SYNC);
  const encoder = encoding.createEncoder();
  encoding.writeVarUint(encoder, MESSAGE_SYNC);
  syncProtocol.readSyncMessage(decoder, encoder, doc, 'relay-fixture');
}

/** True if the spy saw y-protocols swallow a Yjs decode/apply error. */
function sawSwallowedYjsError(spy: { mock: { calls: unknown[][] } }): boolean {
  return spy.mock.calls.some(
    (call) => typeof call[0] === 'string' && call[0].includes(SWALLOWED_ERROR),
  );
}

interface PmMarkJson {
  type: string;
  attrs?: Record<string, unknown>;
}
interface PmNodeJson {
  type: string;
  attrs?: Record<string, unknown>;
  content?: PmNodeJson[];
  marks?: PmMarkJson[];
  text?: string;
}

const HEX_COLOR = /^#([0-9a-f]{6})$/i;

/**
 * Representational-only color normalization: CSSStyleDeclaration (jsdom and
 * real browsers alike) reserializes a hex style value to `rgb(r, g, b)`, so
 * the HTML-parse leg reads `rgb(253, 230, 138)` where the CRDT carries the
 * authored `#fde68a`. Both paint identically — the value, not its spelling,
 * is the contract.
 */
function normalizeColor(value: unknown): unknown {
  if (typeof value !== 'string') return value;
  const match = HEX_COLOR.exec(value);
  if (!match) return value;
  const int = parseInt(match[1] as string, 16);
  return `rgb(${(int >> 16) & 0xff}, ${(int >> 8) & 0xff}, ${int & 0xff})`;
}

function normalizeAttrs(attrs: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(Object.entries(attrs).map(([k, v]) => [k, normalizeColor(v)]));
}

/**
 * Sort every `marks` array by (type, attrs) and normalize color spellings.
 * ProseMirror's DOM parser ranks marks by schema order while y-prosemirror
 * emits them in CRDT-attribute order — the set is the contract, the ordering
 * is presentational.
 */
function normalizeMarkOrder(node: PmNodeJson): PmNodeJson {
  const out: PmNodeJson = { ...node };
  if (out.attrs !== undefined) {
    out.attrs = normalizeAttrs(out.attrs);
  }
  if (out.marks) {
    out.marks = [...out.marks]
      .map((mark) =>
        mark.attrs !== undefined ? { ...mark, attrs: normalizeAttrs(mark.attrs) } : mark,
      )
      .sort((a, b) =>
        `${a.type}${JSON.stringify(a.attrs ?? {})}`.localeCompare(
          `${b.type}${JSON.stringify(b.attrs ?? {})}`,
        ),
      );
  }
  if (out.content) {
    out.content = out.content.map(normalizeMarkOrder);
  }
  return out;
}

/** The editor's real HTML ingestion: a headless Tiptap editor fed `html`. */
function pmJsonFromHtml(html: string): PmNodeJson {
  const element = document.createElement('div');
  document.body.appendChild(element);
  const editor = new Editor({ element, extensions, content: html });
  try {
    return normalizeMarkOrder(editor.getJSON() as PmNodeJson);
  } finally {
    editor.destroy();
    element.remove();
  }
}

/** The editor's real CRDT read: y-prosemirror over the prose fragment. */
function pmJsonFromYDoc(doc: YDoc, pageId: string): PmNodeJson {
  const fragment = doc.getXmlFragment(`prose:${pageId}`);
  return normalizeMarkOrder(
    yXmlFragmentToProseMirrorRootNode(fragment, schema).toJSON() as PmNodeJson,
  );
}

describe('relay↔editor yjs wire contract (JP-326)', () => {
  const scenarios = loadScenarios();

  it('discovers the fixture corpus', () => {
    expect(scenarios.map((s) => s.name)).toContain('seed-parity');
    expect(scenarios.map((s) => s.name)).toContain('structural-verbs');
    expect(scenarios.map((s) => s.name)).toContain('page-rewrite');
    expect(scenarios.map((s) => s.name)).toContain('poison');
  });

  for (const scenario of scenarios.filter((s) => !s.meta.poison)) {
    describe(scenario.name, () => {
      const { meta } = scenario;
      const pageId = meta.pageId;
      if (pageId === null || meta.expectedHtml === null) {
        throw new Error(`${scenario.name}: non-poison scenario must carry pageId + expectedHtml`);
      }
      const expectedHtml = readFileSync(join(scenario.dir, meta.expectedHtml), 'utf8');

      it('sidecar decodes via the prefetch header-strip and applies cleanly', () => {
        const update = stripSidecarHeader(readBytes(scenario, meta.sidecar));
        expect(update).not.toBeNull();
        const doc = new YDoc();
        expect(() => applyUpdate(doc, update as Uint8Array)).not.toThrow();
      });

      it('every broadcast frame survives the production readSyncMessage path', () => {
        const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
        try {
          const doc = new YDoc();
          for (const frameRel of meta.frames) {
            applyFrameLikeProduction(doc, readBytes(scenario, frameRel));
          }
          expect(
            sawSwallowedYjsError(spy),
            'y-protocols swallowed a decode/apply error — the relay emitted bytes yjs cannot handle',
          ).toBe(false);
        } finally {
          spy.mockRestore();
        }
      });

      it('frame replay and sidecar converge to the same editor-visible state', () => {
        const fromFrames = new YDoc();
        for (const frameRel of meta.frames) {
          applyFrameLikeProduction(fromFrames, readBytes(scenario, frameRel));
        }
        const fromSidecar = new YDoc();
        applyUpdate(fromSidecar, stripSidecarHeader(readBytes(scenario, meta.sidecar)) as Uint8Array);
        expect(pmJsonFromYDoc(fromFrames, pageId)).toEqual(pmJsonFromYDoc(fromSidecar, pageId));
      });

      it("editor's CRDT read matches the relay's own HTML projection", () => {
        // The triangle: relay CRDT state → y-prosemirror → PM JSON must equal
        // relay HTML projection → Tiptap parse → PM JSON. A divergence means
        // browsers see something different from what the relay believes it
        // wrote (the silent-loss class JP-432 exists to kill).
        const doc = new YDoc();
        applyUpdate(doc, stripSidecarHeader(readBytes(scenario, meta.sidecar)) as Uint8Array);
        expect(pmJsonFromYDoc(doc, pageId)).toEqual(pmJsonFromHtml(expectedHtml));
      });
    });
  }

  describe('poison (yrs-only ContentMove, wire ref 11)', () => {
    const scenario = scenarios.find((s) => s.meta.poison);
    if (!scenario) throw new Error('poison scenario missing from corpus');
    const { meta } = scenario;

    it('is detected loudly on the prefetch path — applyUpdate throws, never silent', () => {
      const update = stripSidecarHeader(readBytes(scenario, meta.sidecar));
      expect(update).not.toBeNull();
      // If this stops throwing, yjs learned to decode ref 11 — re-evaluate the
      // corpus (and the relay-side "never emit yrs-only structs" rule) rather
      // than deleting the test.
      expect(() => applyUpdate(new YDoc(), update as Uint8Array)).toThrow();
    });

    it('is swallowed as a console.error on the WS path — the documented production gap', () => {
      // This pins today's behavior: UnifiedSyncProvider passes no errorHandler,
      // so a poisoned broadcast turns into a silent console.error and the
      // client's sync clock jams behind the undecodable struct. If this
      // assertion starts failing, the production path changed — update the
      // harness (and the incident notes) deliberately.
      const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
      try {
        const doc = new YDoc();
        for (const frameRel of meta.frames) {
          applyFrameLikeProduction(doc, readBytes(scenario, frameRel));
        }
        expect(sawSwallowedYjsError(spy)).toBe(true);
      } finally {
        spy.mockRestore();
      }
    });
  });
});
